config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Defines the root path route ("/")
  resources :books
  resources :users, only: %i[edit update destroy]
  get '/logsedit', to: 'pages#logsedit'
  get '/profile', to: 'users#profile'
  get '/search', to: 'pages#search'
  get '/query', to: 'pages#query'
  get '/barcode', to: 'pages#barcode'
  get '/scrape', to: 'pages#scrape'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :author, presence: true
  validates :publisher, presence: true
  # validates :user_id, uniqueness: true
  validates :price, presence: true, numericality: { only_integer: true }
  enum :status, { log: 0, bookmark: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :books, dependent: :destroy

  validates :email, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  validates :user_name, presence: true, length: { minimum: 1 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization
  include ActionController::RequestForgeryProtection
  protect_from_forgery with: :exception

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name])
  end

  def set_csrf_token_header
    response.set_header('X-CSRF-Token', form_authenticity_token)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  # skip_before_action :verify_authenticity_token
  protect_from_forgery
  after_action :set_csrf_token_header

  def index
    @books = policy_scope(Book)
  end

  def show
    @book = Book.last
    @book = Book.new(book_params)
    @bookmark = Bookmark.new
    @log = Log.new
    @not_duplicated_bookmark = not_duplicated_bookmark?
    @not_duplicated_log = not_duplicated_log?
    authorize @book
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    @duplicate_book = Book.where(title: @book.title, author: @book.author, user: current_user).first
    # nilのパターン
    authorize @book
    if @duplicate_book.nil?
      @book.save
      flash.now[:notice] = "『#{@book.title}』を記録しました！"
      render :index
      # redirect_to barcode_path
      # POSTリクエストからのリダイレクトはGETリクエストになってしまうのでだめ。
    elsif @duplicate_book && @duplicate_book.status == @book.status
    # 既に要素は存在するかつstatusも一緒のパターン -> インスタンスは生成しない
      flash.now[:notice] = "『#{@book.title}』はすでに通帳に記録されています。"
      render :index
    elsif @duplicate_book && @duplicate_book.status != @book.status
    # 既に要素は存在するが、statusがことなるパターン-> インスタンスは生成せず、statusを切り替える。
      # if @duplicate_book.bookmark?
        # @duplicate_book.log!
        # flash[:notice] = "ブックマークされていた本を通帳に記録しました。"
      # else
        # @duplicate_book.log!
        # flash[:notice] = "通帳に記録されていた本をブックマークへと移動しました。"
      # end
      @duplicate_book.bookmark? ?  @duplicate_book.log! : @duplicate_book.bookmark!
    end



    # @book.user_id = 2
    # respond_to do |format|
    # raise
      # format.html
      # format.json { render json: @book }
    # end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :publisher, :price, :image_url, :status)
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_book, only: %i[new create]
  protect_from_forgery

  def index
    @user = current_user
    @logs = policy_scope(Log).where(user: @user)
    @prices = @logs.map {|log| log.book.original_price }
    @total_sum = @prices.sum
  end

  def new
    @log = Log.new
    authorize @log
  end

  def create
    @log = Log.new
    @log.book = @book
    @log.user = current_user
    authorize @log
    @log.save
    redirect_to logs_path
  end

  def destroy
    @log = Log.find(params[:id])
    authorize @log
    @log.destroy
    redirect_to logsedit_path, status: :see_other
  end

  private

  def set_book
    # finding_book = Book.last
    @book = Book.last
  end

  def book_params
    params.permit(:title, :author, :publisher, :price, :image_url, :status)
  end
end

app/controllers/pages_controller.rb
require "open-uri"
require "nokogiri"

class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def search
  end

  def query
    @books = Book.all
  end

  def barcode
    # @scrape_result = scrape_barcode_result
  end

  def logsedit
    @user = current_user
    @logs = policy_scope(Log).where(user: @user)
  end

  private

  def scrape_barcode_result
    url = "http://localhost:3000/barcode"
    html_content = URI.open(url).read
    doc = Nokogiri::HTML.parse(html_content)
    return doc
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    @user = current_user
    authorize @user
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update(user_params)
      flash[:notice] = "Hey #{@user.first_name}, your account was successfully updated"
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@book, @bookmark] do |f| %>
  <%= f.submit :submit,  value: "+ Bookmark" %>
<% end %>

app/views/books/_book_card.html.erb
<ul class="books-index">
  <% @books.each do |book| %>
    <li>
      <div class="bookcard">
        <div class="bookimg">
          <span></span>
        </div>
        <div class="bookinfo">
          <p class="bookinfo__title"><%= book.title %></p>
          <p class="bookinfo__author"><%= book.author %></p>
          <p class="bookinfo__publisher"><%= book.publisher %></p>
          <div class="bookinfo__buttons">
          <%= link_to "detail", book_path(book), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/books/index.html.erb
<div class="container">
  <%= react_component("atoms/logs/Log") %>
</div>

app/views/books/show.html.erb
<h1>this books detail!</h1>
<%# <%= link_to "+Bookmark", new_book_bookmark_path(@book) %>
<%# <% if @not_duplicated_bookmark && @not_duplicated_log %> %>
  <%# <%= render 'bookmarks/new', book: @book, bookmark: @bookmark %> %>
<%# <% end %> %>
<%# <% if @not_duplicated_log %> %>
  <%# <%= render 'logs/new', book: @book, log: @log %> %>
<%# <% end %> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPicbookPassbook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
    <%= yield %>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
  </body>
</html>

app/views/logs/_edit_passbook_column.html.erb
<div class="d-flex flex-column">
  <% @logs.each do |log| %>
    <ul class="list-inline">
      <li class="date">
        <p><%= log.created_at.to_s.split(" ")[0] %></p>
      </li>
      <li class="title">
        <p><%= log.book.title %></p>
      </li>
      <li class="author">
        <p><%= log.book.author %></p>
      </li>
      <li class="price">
        <p><%= log.book.original_price %></p>
      </li>
      <li>
        <%= button_to log_path(log), method: :delete, data: { turbo: false } do %>
          <i class="fa-solid fa-square-xmark"></i>
        <% end %>
      </li>
    </ul>
  <% end %>
</div>

app/views/logs/_new.html.erb
<%= simple_form_for [book, log] do |f| %>
  <%= f.submit :submit,  value: "+ Log", class: "btn btn-primary" %>
<% end %>

app/views/logs/_passbook.html.erb
<div class="d-flex">
  <%= render 'passbook_column', logs: @logs %>
</div>

app/views/logs/_passbook_column.html.erb
<div class="d-flex flex-column">
  <% @logs.each do |log| %>
    <ul class="list-inline">
      <li class="date">
        <p><%= log.created_at.to_s.split(" ")[0] %></p>
      </li>
      <li class="title">
        <p><%= log.book.title %></p>
      </li>
      <li class="author">
        <p><%= log.book.author %></p>
      </li>
      <li class="price">
        <p><%= log.book.original_price %></p>
      </li>
    </ul>
  <% end %>
</div>

app/views/logs/index.html.erb
<h2>Welcome, <%= @user.user_name %> !!</h2>
<h2>What did you read today?</h2>

<h1>Your Logs!! and Home page!!</h1>
<%= link_to 'edit', logsedit_path %>
<%= render 'passbook' %>

app/views/pages/barcode.html.erb
<%= react_component("scanners/ScannerIndex") %>

app/views/pages/home.html.erb
<div class="container">
  <h2>What did you read today?</h2>
  <h2>Keep your reading logs with VALUE!!</h2>
</div>

app/views/pages/logsedit.html.erb
<h1>logsedit</h1>
<%= render 'logs/edit_passbook_column', logs: @logs %>

app/views/pages/query.html.erb
<div class="searcharea">
  <%= react_component("molecules/queries/query") %>
</div>

app/views/pages/scrape.html.erb
<h1>scrape data!</h1>

<button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">Enable body scrolling</button>

<div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasScrollingLabel">Offcanvas with body scrolling</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <p>Try scrolling the rest of the page to see this option in action.</p>
  </div>
</div>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/search.html.erb
<h1>this is search page!!</h1>
<%= link_to 'search', query_path %>
<%= link_to 'scan', barcode_path %>

<%# <%= react_component("HelloWorld", { greeting: "Hello from react-rails." }) %>
<%# <%= react_component("my_subdirectory/HelloWorld", { greeting: "Hello from react-rails SUBDIRECTORY." }) %>

app/views/pages/statistics.html.erb
<h1>your data!</h1>

<button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">Enable body scrolling</button>

<div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasScrollingLabel">Offcanvas with body scrolling</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <p>Try scrolling the rest of the page to see this option in action.</p>
  </div>
</div>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-lewagon">
  <ul class="navbar-nav me-auto">
    <% if user_signed_in? %>
      <div class="navbar-nav__left">
        <li class="nav-item active">
          <%= link_to books_path, class: "nav-link" do %>
            <i class="fa-solid fa-credit-card"></i>
          <% end %>
        </li>
      </div>

      <%= link_to search_path, class: "nav-link" do %>
        <div class="navbar-nav__center">
          <li class="navbar-nav__center__item nav-item">
            <i class="fa-solid fa-magnifying-glass"></i>
          </li>
        </div>
      <% end %>

      <div class="navbar-nav__right">
        <li class="nav-item">
          <%= link_to books_path, class: "nav-link" do %>
            <i class="fa-solid fa-bookmark"></i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to profile_path, class: "nav-link" do %>
            <i class="fa-solid fa-user"></i>
          <% end %>
        </li>
      </div>

      <%# <li class="nav-item dropdown"> %>
      <%# <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> %>
        <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
      <%# </a> %>
        <%# <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown"> %>
          <%# <%= link_to "Action", "#", class: "dropdown-item" %>
          <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
          <%# <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
        <%# </div> %>
      <%# </li> %>
    <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/edit.html.erb
<h1>
  User edit page!!
</h1>

app/views/users/profile.html.erb
<div class="header">
  <div class="avatar">

  </div>
</div>

<div class="container">
  <h2><%= current_user.user_name %></h2>
  <ul class="profile__items">
    <li>
      <%= link_to edit_user_path(current_user) do %>
        <i class="fa-solid fa-gear"></i> Your Account
      <% end %>
    </li>

    <li>
      <%= link_to  new_user_password_path do %>
        <i class="fa-solid fa-key"></i> Change Your Password
      <% end %>
    </li>

    <li>
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
        <i class="fa-solid fa-right-from-bracket"></i> Log out
      <% end%>
    </li>
   </ul>
</div>